services:
  - type: web
    name: itcg-crf
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120 --workers 1"
    nativePackages:
      - wkhtmltopdf